/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jgranados.ipc1_01_2024_a.threads.tragamonedas.frontend;

import com.jgranados.ipc1_01_2024_a.threads.tragamonedas.backend.Tragamonedas;
import javax.swing.JOptionPane;

/**
 *
 * @author jose
 */
public class TragamonedasFrame extends javax.swing.JFrame {

    private Tragamonedas tragamonedas;
    /**
     * Creates new form TragamonedasFrame
     */
    public TragamonedasFrame() {
        initComponents();
        tragamonedas = new Tragamonedas(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCasillas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCantMonedas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spnApuesta = new javax.swing.JSpinner();
        btnIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlCasillas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCasillas.setLayout(new java.awt.GridLayout(1, 3));

        jLabel1.setText("Monedas:");

        lblCantMonedas.setText("0.0");

        jLabel2.setText("Apuesta:");

        spnApuesta.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        btnIniciar.setText("Iniciar!");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCasillas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblCantMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(spnApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIniciar)
                        .addGap(0, 114, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(pnlCasillas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCantMonedas)
                    .addComponent(jLabel2)
                    .addComponent(spnApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciar))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        int apuesta = (Integer) spnApuesta.getValue();
        tragamonedas.iniciarJuego(apuesta);
        activarControles(false);
    }//GEN-LAST:event_btnIniciarActionPerformed

    public void agregarCasillas(Casilla casilla1, Casilla casilla2, Casilla casilla3) {
        pnlCasillas.removeAll();
        
        pnlCasillas.add(casilla1);
        pnlCasillas.add(casilla2);
        pnlCasillas.add(casilla3);
        pnlCasillas.validate();
        pnlCasillas.repaint();
    }
    
    public void avisarGanancia(int ganancia, int cantidadMonedas) {
        JOptionPane.showMessageDialog(this, "Ganó " + ganancia + " monedas");
        lblCantMonedas.setText(cantidadMonedas + "");
    }
    
    public void avisarPerdida(int apuesta) {
        JOptionPane.showMessageDialog(this, "Perdió " + apuesta + " monedas");
    }
    
    public void activarControles(boolean activar) {
        this.spnApuesta.setEnabled(activar);
        this.btnIniciar.setEnabled(activar);
    }
    
    public void toggleControles() {
        this.spnApuesta.setEnabled(!spnApuesta.isEnabled());
        this.btnIniciar.setEnabled(!btnIniciar.isEnabled());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCantMonedas;
    private javax.swing.JPanel pnlCasillas;
    private javax.swing.JSpinner spnApuesta;
    // End of variables declaration//GEN-END:variables
}
