/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jgranados.ipc1_01_2024_a.threads.threadsyswing.frontend;

/**
 *
 * @author jose
 */
public class CajerosFrame extends javax.swing.JFrame {

    /**
     * Creates new form CajerosFrame
     */
    public CajerosFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarCajero = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlCajeros = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hilos y Theads");

        btnAgregarCajero.setText("Agregar cajero");
        btnAgregarCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCajeroActionPerformed(evt);
            }
        });

        pnlCajeros.setLayout(new java.awt.GridLayout(0, 4));
        jScrollPane1.setViewportView(pnlCajeros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregarCajero)
                        .addGap(0, 435, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnAgregarCajero)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCajeroActionPerformed
        CajeroPanel cajeroNuevo = new CajeroPanel();
        this.pnlCajeros.add(cajeroNuevo);
        this.pnlCajeros.repaint();
        Thread hiloPanel = new Thread(cajeroNuevo);
        hiloPanel.start();
    }//GEN-LAST:event_btnAgregarCajeroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCajero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlCajeros;
    // End of variables declaration//GEN-END:variables
}
