/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.jgranados.ipc1_01_2024_a.threads.threadsyswing.frontend;

import java.time.LocalDateTime;
import java.util.Random;

/**
 *
 * @author jose
 */
public class CajeroPanel extends javax.swing.JPanel implements Runnable {

    private int[] productos;
    private String nombre;
    
    
    /**
     * Creates new form CajeroPanel
     */
    public CajeroPanel() {
        nombre = LocalDateTime.now().toString();
        productos = new int[5];
        Random random = new Random();
        for (int i = 0; i < productos.length; i++) {
            productos[i] = random.nextInt(2, 9);
        }
        initComponents();
        lblNombre.setText(nombre);
    }
    
    @Override
    public void run() {
        procesarProductos();
    }

    private void procesarProductos() {
        try {
            for (int i = 0; i < productos.length; i++) {
                int producto = productos[i];
                lblProducto.setText(producto + "");
                Thread.sleep(producto * 1000);
            }
            lblProducto.setText("Finalizado");
        } catch (InterruptedException e) {
            // manejar correctamente el error
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(125, 125));
        setMinimumSize(new java.awt.Dimension(125, 125));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(125, 125));
        setRequestFocusEnabled(false);

        lblNombre.setText("jLabel1");

        lblProducto.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addComponent(lblProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblNombre)
                .addGap(46, 46, 46)
                .addComponent(lblProducto)
                .addContainerGap(194, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void especificarLblProducto(String valor) {
        lblProducto.setText(valor);
    }
    
    public void especificarLblNombre(String valor) {
        lblNombre.setText(valor);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblProducto;
    // End of variables declaration//GEN-END:variables
}
